''' 
This is an autogenerated file. 
This file was generated by convert_json_to_sql.py at 07/01/14 19:10:53. 
Any edits will be overwritten. 
''' 
 
import sqlite3 
 
con = sqlite3.connect('expenses.db') 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	comment, 
 	expense_date) 
VALUES  
	('initial purchase', 
	1380.0, 
	'cost of car', 
	'06/11/13')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	comment, 
 	expense_date) 
VALUES  
	('initial purchase', 
	60.0, 
	'delivery', 
	'06/11/13')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	comment, 
 	expense_date) 
VALUES  
	('insurance', 
	792.06, 
	'insurance for 1 year starting 8pm', 
	'06/11/13')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	mileage, 
 	expense_date) 
VALUES  
	('petrol', 
	44.02, 
	44233, 
	'06/11/13')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	comment, 
 	expense_date) 
VALUES  
	('maintenance', 
	2.0, 
	'window scraper', 
	'06/11/13')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	comment, 
 	expense_date) 
VALUES  
	('maintenance', 
	6.0, 
	'window cleaning liquid', 
	'06/11/13')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	expense_date) 
VALUES  
	('parking', 
	4.5, 
	'10/11/13')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	mileage, 
 	expense_date) 
VALUES  
	('petrol', 
	41.53, 
	44527, 
	'14/11/13')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	comment, 
 	expense_date) 
VALUES  
	('maintenance', 
	3.99, 
	'oil based lubricant', 
	'16/11/13')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	expense_date) 
VALUES  
	('parking', 
	6.5, 
	'19/11/13')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	mileage, 
 	expense_date) 
VALUES  
	('petrol', 
	45.55, 
	44857, 
	'20/11/13')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	mileage, 
 	expense_date) 
VALUES  
	('petrol', 
	46.38, 
	45209, 
	'24/11/13')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	expense_date) 
VALUES  
	('parking', 
	1.5, 
	'24/11/13')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	expense_date) 
VALUES  
	('parking', 
	1.5, 
	'01/12/13')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	mileage, 
 	expense_date) 
VALUES  
	('petrol', 
	45.1, 
	45540, 
	'03/12/13')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	expense_date) 
VALUES  
	('parking', 
	2.8, 
	'07/12/13')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	mileage, 
 	expense_date) 
VALUES  
	('petrol', 
	45.28, 
	45888, 
	'09/12/13')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	mileage, 
 	expense_date) 
VALUES  
	('petrol', 
	41.44, 
	46189, 
	'11/12/13')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	mileage, 
 	expense_date) 
VALUES  
	('petrol', 
	49.0, 
	46546, 
	'19/12/13')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	comment, 
 	expense_date) 
VALUES  
	('profit', 
	360.0, 
	'Tessella expenses', 
	'20/12/13')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	expense_date) 
VALUES  
	('parking', 
	1.8, 
	'21/12/13')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	comment, 
 	expense_date) 
VALUES  
	('maintenance', 
	1.49, 
	'demister', 
	'22/12/13')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	expense_date) 
VALUES  
	('parking', 
	1.3, 
	'02/01/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	mileage, 
 	expense_date) 
VALUES  
	('petrol', 
	38.72, 
	46821, 
	'03/01/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	comment, 
 	expense_date) 
VALUES  
	('maintenance', 
	2.5, 
	'smelly car tree', 
	'10/01/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	mileage, 
 	expense_date) 
VALUES  
	('petrol', 
	31.64, 
	47025, 
	'15/01/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	mileage, 
 	expense_date) 
VALUES  
	('petrol', 
	44.54, 
	47358, 
	'23/01/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	comment, 
 	expense_date) 
VALUES  
	('profit', 
	432.0, 
	'Tessella expenses', 
	'28/01/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	mileage, 
 	expense_date) 
VALUES  
	('petrol', 
	40.6, 
	47648, 
	'03/02/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	mileage, 
 	expense_date) 
VALUES  
	('petrol', 
	47.31, 
	48012, 
	'07/02/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	mileage, 
 	expense_date) 
VALUES  
	('petrol', 
	43.39, 
	48337, 
	'14/02/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	expense_date) 
VALUES  
	('parking', 
	8.0, 
	'18/02/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	comment, 
 	expense_date) 
VALUES  
	('profit', 
	288.0, 
	'Tessella expenses', 
	'26/02/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	comment, 
 	expense_date) 
VALUES  
	('tax', 
	77.0, 
	'Tax disc for 6 months starting 01/03/14', 
	'26/02/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	mileage, 
 	expense_date) 
VALUES  
	('petrol', 
	41.27, 
	48634, 
	'26/02/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	comment, 
 	expense_date) 
VALUES  
	('maintenance', 
	14.0, 
	'wheel trims', 
	'09/03/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	comment, 
 	expense_date) 
VALUES  
	('maintenance', 
	3.99, 
	'wheel trim security kit', 
	'09/03/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	comment, 
 	expense_date) 
VALUES  
	('maintenance', 
	4.99, 
	'guy fitting wheel trims on car', 
	'09/03/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	comment, 
 	expense_date) 
VALUES  
	('maintenance', 
	4.99, 
	'smelly car tree', 
	'09/03/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	mileage, 
 	expense_date) 
VALUES  
	('petrol', 
	43.2, 
	48934, 
	'11/03/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	expense_date) 
VALUES  
	('parking', 
	1.5, 
	'15/03/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	mileage, 
 	expense_date) 
VALUES  
	('petrol', 
	39.18, 
	49230, 
	'20/03/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	comment, 
 	expense_date) 
VALUES  
	('profit', 
	324.0, 
	'Tessella expenses', 
	'26/03/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	mileage, 
 	litres, 
 	expense_date) 
VALUES  
	('petrol', 
	38.78, 
	49514, 
	30.78, 
	'28/03/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	mileage, 
 	litres, 
 	expense_date) 
VALUES  
	('petrol', 
	38.06, 
	49827, 
	30.23, 
	'01/04/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	mileage, 
 	litres, 
 	expense_date) 
VALUES  
	('petrol', 
	40.55, 
	50125, 
	32.73, 
	'09/04/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	expense_date) 
VALUES  
	('parking', 
	2.7, 
	'09/04/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	expense_date) 
VALUES  
	('parking', 
	3.5, 
	'11/04/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	mileage, 
 	litres, 
 	expense_date) 
VALUES  
	('petrol', 
	48.0, 
	50493, 
	38.13, 
	'11/04/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	comment, 
 	expense_date) 
VALUES  
	('profit', 
	48.0, 
	'Pia and Villem paid for petrol', 
	'11/04/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	mileage, 
 	litres, 
 	expense_date) 
VALUES  
	('petrol', 
	45.15, 
	50830, 
	35.05, 
	'18/04/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	comment, 
 	expense_date) 
VALUES  
	('profit', 
	10.0, 
	'Marcels pixie friend paid for lift', 
	'18/04/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	expense_date) 
VALUES  
	('parking', 
	7.0, 
	'19/04/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	expense_date) 
VALUES  
	('parking', 
	2.9, 
	'21/04/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	comment, 
 	expense_date) 
VALUES  
	('profit', 
	216.0, 
	'Tessella expenses', 
	'26/04/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	comment, 
 	expense_date) 
VALUES  
	('fine', 
	65.0, 
	'Camden parking fine', 
	'26/04/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	comment, 
 	expense_date) 
VALUES  
	('maintenance', 
	4.99, 
	'car wash', 
	'03/05/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	expense_date) 
VALUES  
	('parking', 
	1.5, 
	'03/05/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	expense_date) 
VALUES  
	('parking', 
	3.5, 
	'03/05/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	mileage, 
 	expense_date) 
VALUES  
	('petrol', 
	49.02, 
	51142, 
	'03/05/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	expense_date) 
VALUES  
	('parking', 
	1.6, 
	'04/05/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	mileage, 
 	expense_date) 
VALUES  
	('petrol', 
	42.61, 
	51506, 
	'15/05/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	expense_date) 
VALUES  
	('parking', 
	0.9, 
	'17/05/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	expense_date) 
VALUES  
	('parking', 
	1.5, 
	'17/05/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	mileage, 
 	expense_date) 
VALUES  
	('petrol', 
	42.33, 
	51872, 
	'22/05/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	expense_date) 
VALUES  
	('parking', 
	4.0, 
	'24/05/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	expense_date) 
VALUES  
	('parking', 
	3.5, 
	'30/05/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	expense_date) 
VALUES  
	('parking', 
	4.0, 
	'31/05/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	mileage, 
 	expense_date) 
VALUES  
	('petrol', 
	41.91, 
	52201, 
	'04/06/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	expense_date) 
VALUES  
	('parking', 
	3.5, 
	'13/06/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	mileage, 
 	expense_date) 
VALUES  
	('petrol', 
	39.15, 
	52525, 
	'15/06/14')""") 
 
con.execute("""INSERT INTO expenses
	(expense_type, 
 	amount, 
 	expense_date) 
VALUES  
	('parking', 
	3.5, 
	'20/06/14')""") 
 
con.commit()